apiVersion: v1
kind: Namespace
metadata:
  name: monitor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-prometheus
  namespace: monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app-prometheus
  template:
    metadata:
      labels:
        app: demo-app-prometheus
        description: "Endpoint to test API is /weatherforecast"
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
    spec:
      containers:
      - name: demo-app-prometheus
        image: lgmorand/demoappprometheus:1.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-prometheus-svc
  namespace: monitor
  description: "Endpoint to test API is /weatherforecast"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: demo-app-prometheus
